// ============================================
// MeinkraftAI — Complete Minecraft Database
// ============================================

const DB = {
  // ── BLOCKS ── (image = wiki texture URL)
  blocks: [
    {id:"stone",name:"Pierre",cat:"building",hard:1.5,tool:"Pioche",col:"#808080",tex:"https://minecraft.wiki/images/thumb/Stone_JE6_BE5.png/128px-Stone_JE6_BE5.png"},
    {id:"granite",name:"Granite",cat:"building",hard:1.5,tool:"Pioche",col:"#9A6C50",tex:"https://minecraft.wiki/images/thumb/Granite_JE4_BE6.png/128px-Granite_JE4_BE6.png"},
    {id:"diorite",name:"Diorite",cat:"building",hard:1.5,tool:"Pioche",col:"#C8C8C8",tex:"https://minecraft.wiki/images/thumb/Diorite_JE4_BE6.png/128px-Diorite_JE4_BE6.png"},
    {id:"andesite",name:"Andésite",cat:"building",hard:1.5,tool:"Pioche",col:"#888888",tex:"https://minecraft.wiki/images/thumb/Andesite_JE4_BE6.png/128px-Andesite_JE4_BE6.png"},
    {id:"grass_block",name:"Bloc d'Herbe",cat:"nature",hard:0.6,tool:"Pelle",col:"#5D8C3E",tex:"https://minecraft.wiki/images/thumb/Grass_Block_JE7.png/128px-Grass_Block_JE7.png"},
    {id:"dirt",name:"Terre",cat:"nature",hard:0.5,tool:"Pelle",col:"#8B6F47",tex:"https://minecraft.wiki/images/thumb/Dirt_JE3_BE6.png/128px-Dirt_JE3_BE6.png"},
    {id:"cobblestone",name:"Pierres",cat:"building",hard:2,tool:"Pioche",col:"#777777",tex:"https://minecraft.wiki/images/thumb/Cobblestone_JE5_BE6.png/128px-Cobblestone_JE5_BE6.png"},
    {id:"oak_planks",name:"Planches de Chêne",cat:"wood",hard:2,tool:"Hache",col:"#BC9458",tex:"https://minecraft.wiki/images/thumb/Oak_Planks_JE6.png/128px-Oak_Planks_JE6.png"},
    {id:"spruce_planks",name:"Planches d'Épicéa",cat:"wood",hard:2,tool:"Hache",col:"#6B4F2A",tex:"https://minecraft.wiki/images/thumb/Spruce_Planks_JE5.png/128px-Spruce_Planks_JE5.png"},
    {id:"birch_planks",name:"Planches de Bouleau",cat:"wood",hard:2,tool:"Hache",col:"#D4C483",tex:"https://minecraft.wiki/images/thumb/Birch_Planks_JE5.png/128px-Birch_Planks_JE5.png"},
    {id:"jungle_planks",name:"Planches de Jungle",cat:"wood",hard:2,tool:"Hache",col:"#9A6C3E",tex:"https://minecraft.wiki/images/thumb/Jungle_Planks_JE5.png/128px-Jungle_Planks_JE5.png"},
    {id:"acacia_planks",name:"Planches d'Acacia",cat:"wood",hard:2,tool:"Hache",col:"#AD5E24",tex:"https://minecraft.wiki/images/thumb/Acacia_Planks_JE5.png/128px-Acacia_Planks_JE5.png"},
    {id:"dark_oak_planks",name:"Planches Chêne Noir",cat:"wood",hard:2,tool:"Hache",col:"#3E2812",tex:"https://minecraft.wiki/images/thumb/Dark_Oak_Planks_JE5.png/128px-Dark_Oak_Planks_JE5.png"},
    {id:"oak_log",name:"Bûche de Chêne",cat:"wood",hard:2,tool:"Hache",col:"#6B511F",tex:"https://minecraft.wiki/images/thumb/Oak_Log_%28vertical%29_JE7_BE6.png/128px-Oak_Log_%28vertical%29_JE7_BE6.png"},
    {id:"spruce_log",name:"Bûche d'Épicéa",cat:"wood",hard:2,tool:"Hache",col:"#3E2812",tex:"https://minecraft.wiki/images/thumb/Spruce_Log_%28vertical%29_JE6_BE5.png/128px-Spruce_Log_%28vertical%29_JE6_BE5.png"},
    {id:"bedrock",name:"Bedrock",cat:"nature",hard:-1,tool:"Aucun",col:"#333333",tex:"https://minecraft.wiki/images/thumb/Bedrock_JE4_BE4.png/128px-Bedrock_JE4_BE4.png"},
    {id:"sand",name:"Sable",cat:"nature",hard:0.5,tool:"Pelle",col:"#DBD3A0",tex:"https://minecraft.wiki/images/thumb/Sand_JE4_BE6.png/128px-Sand_JE4_BE6.png"},
    {id:"gravel",name:"Gravier",cat:"nature",hard:0.6,tool:"Pelle",col:"#888078",tex:"https://minecraft.wiki/images/thumb/Gravel_JE7_BE5.png/128px-Gravel_JE7_BE5.png"},
    {id:"gold_ore",name:"Minerai d'Or",cat:"ore",hard:3,tool:"Pioche Fer",col:"#FCDB5C",tex:"https://minecraft.wiki/images/thumb/Gold_Ore_JE8_BE7.png/128px-Gold_Ore_JE8_BE7.png"},
    {id:"iron_ore",name:"Minerai de Fer",cat:"ore",hard:3,tool:"Pioche Pierre",col:"#D8AF93",tex:"https://minecraft.wiki/images/thumb/Iron_Ore_JE8_BE7.png/128px-Iron_Ore_JE8_BE7.png"},
    {id:"coal_ore",name:"Minerai de Charbon",cat:"ore",hard:3,tool:"Pioche",col:"#2A2A2A",tex:"https://minecraft.wiki/images/thumb/Coal_Ore_JE8_BE7.png/128px-Coal_Ore_JE8_BE7.png"},
    {id:"diamond_ore",name:"Minerai de Diamant",cat:"ore",hard:3,tool:"Pioche Fer",col:"#5CE5E5",tex:"https://minecraft.wiki/images/thumb/Diamond_Ore_JE8_BE7.png/128px-Diamond_Ore_JE8_BE7.png"},
    {id:"emerald_ore",name:"Minerai d'Émeraude",cat:"ore",hard:3,tool:"Pioche Fer",col:"#17DD62",tex:"https://minecraft.wiki/images/thumb/Emerald_Ore_JE8_BE7.png/128px-Emerald_Ore_JE8_BE7.png"},
    {id:"redstone_ore",name:"Minerai de Redstone",cat:"ore",hard:3,tool:"Pioche Fer",col:"#FF0000",tex:"https://minecraft.wiki/images/thumb/Redstone_Ore_JE8_BE7.png/128px-Redstone_Ore_JE8_BE7.png"},
    {id:"lapis_ore",name:"Minerai de Lapis",cat:"ore",hard:3,tool:"Pioche Pierre",col:"#1A3C8C",tex:"https://minecraft.wiki/images/thumb/Lapis_Lazuli_Ore_JE7_BE5.png/128px-Lapis_Lazuli_Ore_JE7_BE5.png"},
    {id:"copper_ore",name:"Minerai de Cuivre",cat:"ore",hard:3,tool:"Pioche Pierre",col:"#C07040",tex:"https://minecraft.wiki/images/thumb/Copper_Ore_JE8_BE7.png/128px-Copper_Ore_JE8_BE7.png"},
    {id:"gold_block",name:"Bloc d'Or",cat:"mineral",hard:3,tool:"Pioche Fer",col:"#FCDB5C",tex:"https://minecraft.wiki/images/thumb/Gold_Block_JE7_BE5.png/128px-Gold_Block_JE7_BE5.png"},
    {id:"iron_block",name:"Bloc de Fer",cat:"mineral",hard:5,tool:"Pioche Pierre",col:"#D8D8D8",tex:"https://minecraft.wiki/images/thumb/Iron_Block_JE6_BE5.png/128px-Iron_Block_JE6_BE5.png"},
    {id:"diamond_block",name:"Bloc de Diamant",cat:"mineral",hard:5,tool:"Pioche Fer",col:"#5CE5E5",tex:"https://minecraft.wiki/images/thumb/Diamond_Block_JE6_BE5.png/128px-Diamond_Block_JE6_BE5.png"},
    {id:"emerald_block",name:"Bloc d'Émeraude",cat:"mineral",hard:5,tool:"Pioche Fer",col:"#17DD62",tex:"https://minecraft.wiki/images/thumb/Emerald_Block_JE6_BE5.png/128px-Emerald_Block_JE6_BE5.png"},
    {id:"redstone_block",name:"Bloc de Redstone",cat:"mineral",hard:5,tool:"Pioche Fer",col:"#FF0000",tex:"https://minecraft.wiki/images/thumb/Redstone_Block_JE5_BE5.png/128px-Redstone_Block_JE5_BE5.png"},
    {id:"netherite_block",name:"Bloc de Netherite",cat:"mineral",hard:50,tool:"Pioche Diamant",col:"#4A3A3A",tex:"https://minecraft.wiki/images/thumb/Netherite_Block_JE2_BE2.png/128px-Netherite_Block_JE2_BE2.png"},
    {id:"glass",name:"Verre",cat:"decoration",hard:0.3,tool:"Aucun",col:"#C8E8FF",tex:"https://minecraft.wiki/images/thumb/Glass_JE4_BE3.png/128px-Glass_JE4_BE3.png"},
    {id:"bricks",name:"Briques",cat:"building",hard:2,tool:"Pioche",col:"#9B4C3C",tex:"https://minecraft.wiki/images/thumb/Bricks_JE6_BE5.png/128px-Bricks_JE6_BE5.png"},
    {id:"stone_bricks",name:"Pierres Taillées",cat:"building",hard:1.5,tool:"Pioche",col:"#7A7A7A",tex:"https://minecraft.wiki/images/thumb/Stone_Bricks_JE5_BE4.png/128px-Stone_Bricks_JE5_BE4.png"},
    {id:"obsidian",name:"Obsidienne",cat:"nature",hard:50,tool:"Pioche Diamant",col:"#1B0B2A",tex:"https://minecraft.wiki/images/thumb/Obsidian_JE4_BE4.png/128px-Obsidian_JE4_BE4.png"},
    {id:"netherrack",name:"Netherrack",cat:"nether",hard:0.4,tool:"Pioche",col:"#6A1A1A",tex:"https://minecraft.wiki/images/thumb/Netherrack_JE3_BE2.png/128px-Netherrack_JE3_BE2.png"},
    {id:"soul_sand",name:"Sable des Âmes",cat:"nether",hard:0.5,tool:"Pelle",col:"#5A4A2A",tex:"https://minecraft.wiki/images/thumb/Soul_Sand_JE4_BE3.png/128px-Soul_Sand_JE4_BE3.png"},
    {id:"glowstone",name:"Pierre Luminescente",cat:"light",hard:0.3,tool:"Aucun",col:"#FFD700",tex:"https://minecraft.wiki/images/thumb/Glowstone_JE4_BE3.png/128px-Glowstone_JE4_BE3.png"},
    {id:"end_stone",name:"Pierre de l'End",cat:"end",hard:3,tool:"Pioche",col:"#DBD6A0",tex:"https://minecraft.wiki/images/thumb/End_Stone_JE3_BE3.png/128px-End_Stone_JE3_BE3.png"},
    {id:"purpur_block",name:"Purpur",cat:"end",hard:1.5,tool:"Pioche",col:"#9A5A9A",tex:"https://minecraft.wiki/images/thumb/Purpur_Block_JE2_BE2.png/128px-Purpur_Block_JE2_BE2.png"},
    {id:"quartz_block",name:"Bloc de Quartz",cat:"building",hard:0.8,tool:"Pioche",col:"#E8E4D8",tex:"https://minecraft.wiki/images/thumb/Quartz_Block_JE5_BE4.png/128px-Quartz_Block_JE5_BE4.png"},
    {id:"smooth_stone",name:"Pierre Lisse",cat:"building",hard:2,tool:"Pioche",col:"#A0A0A0",tex:"https://minecraft.wiki/images/thumb/Smooth_Stone_JE4_BE3.png/128px-Smooth_Stone_JE4_BE3.png"},
    {id:"sandstone",name:"Grès",cat:"building",hard:0.8,tool:"Pioche",col:"#DBD3A0",tex:"https://minecraft.wiki/images/thumb/Sandstone_JE5_BE5.png/128px-Sandstone_JE5_BE5.png"},
    {id:"terracotta",name:"Terre Cuite",cat:"building",hard:1.25,tool:"Pioche",col:"#985B43",tex:"https://minecraft.wiki/images/thumb/Terracotta_JE5_BE4.png/128px-Terracotta_JE5_BE4.png"},
    {id:"white_concrete",name:"Béton Blanc",cat:"building",hard:1.8,tool:"Pioche",col:"#CFD5D6",tex:"https://minecraft.wiki/images/thumb/White_Concrete_JE2.png/128px-White_Concrete_JE2.png"},
    {id:"black_concrete",name:"Béton Noir",cat:"building",hard:1.8,tool:"Pioche",col:"#080A0F",tex:"https://minecraft.wiki/images/thumb/Black_Concrete_JE2.png/128px-Black_Concrete_JE2.png"},
    {id:"red_concrete",name:"Béton Rouge",cat:"building",hard:1.8,tool:"Pioche",col:"#8E2121",tex:"https://minecraft.wiki/images/thumb/Red_Concrete_JE2.png/128px-Red_Concrete_JE2.png"},
    {id:"blue_concrete",name:"Béton Bleu",cat:"building",hard:1.8,tool:"Pioche",col:"#2C2E8F",tex:"https://minecraft.wiki/images/thumb/Blue_Concrete_JE2.png/128px-Blue_Concrete_JE2.png"},
    {id:"yellow_concrete",name:"Béton Jaune",cat:"building",hard:1.8,tool:"Pioche",col:"#F1AF15",tex:"https://minecraft.wiki/images/thumb/Yellow_Concrete_JE2.png/128px-Yellow_Concrete_JE2.png"},
    {id:"gray_concrete",name:"Béton Gris",cat:"building",hard:1.8,tool:"Pioche",col:"#36393D",tex:"https://minecraft.wiki/images/thumb/Gray_Concrete_JE2.png/128px-Gray_Concrete_JE2.png"},
    {id:"crafting_table",name:"Établi",cat:"utility",hard:2.5,tool:"Hache",col:"#BC9458",tex:"https://minecraft.wiki/images/thumb/Crafting_Table_JE4_BE3.png/128px-Crafting_Table_JE4_BE3.png"},
    {id:"furnace",name:"Fourneau",cat:"utility",hard:3.5,tool:"Pioche",col:"#808080",tex:"https://minecraft.wiki/images/thumb/Furnace_%28front%29_JE5.png/128px-Furnace_%28front%29_JE5.png"},
    {id:"chest",name:"Coffre",cat:"storage",hard:2.5,tool:"Hache",col:"#BC9458",tex:"https://minecraft.wiki/images/thumb/Chest_JE4_BE3.png/128px-Chest_JE4_BE3.png"},
    {id:"anvil",name:"Enclume",cat:"utility",hard:5,tool:"Pioche",col:"#3A3A3A",tex:"https://minecraft.wiki/images/thumb/Anvil_JE3_BE3.png/128px-Anvil_JE3_BE3.png"},
    {id:"enchanting_table",name:"Table d'Enchantement",cat:"utility",hard:5,tool:"Pioche",col:"#1A1A2A",tex:"https://minecraft.wiki/images/thumb/Enchanting_Table_%28front%29_JE2.png/128px-Enchanting_Table_%28front%29_JE2.png"},
    {id:"beacon",name:"Balise",cat:"utility",hard:3,tool:"Pioche",col:"#5CE5E5",tex:"https://minecraft.wiki/images/thumb/Beacon_JE5.png/128px-Beacon_JE5.png"},
    {id:"torch",name:"Torche",cat:"light",hard:0,tool:"Aucun",col:"#FFA500",tex:"https://minecraft.wiki/images/thumb/Torch_%28placed%29_JE5.png/64px-Torch_%28placed%29_JE5.png"},
    {id:"lantern",name:"Lanterne",cat:"light",hard:3.5,tool:"Pioche",col:"#FFA500",tex:"https://minecraft.wiki/images/thumb/Lantern_JE2.png/64px-Lantern_JE2.png"},
    {id:"redstone_lamp",name:"Lampe Redstone",cat:"redstone",hard:0.3,tool:"Aucun",col:"#FF8C00",tex:"https://minecraft.wiki/images/thumb/Redstone_Lamp_%28on%29_JE3.png/128px-Redstone_Lamp_%28on%29_JE3.png"},
    {id:"tnt",name:"TNT",cat:"redstone",hard:0,tool:"Aucun",col:"#FF0000",tex:"https://minecraft.wiki/images/thumb/TNT_JE4_BE3.png/128px-TNT_JE4_BE3.png"},
    {id:"piston",name:"Piston",cat:"redstone",hard:1.5,tool:"Pioche",col:"#808080",tex:"https://minecraft.wiki/images/thumb/Piston_%28front%29_JE2.png/128px-Piston_%28front%29_JE2.png"},
    {id:"hopper",name:"Entonnoir",cat:"redstone",hard:3,tool:"Pioche",col:"#808080",tex:"https://minecraft.wiki/images/thumb/Hopper_%28down%29_JE2.png/128px-Hopper_%28down%29_JE2.png"},
    {id:"dispenser",name:"Distributeur",cat:"redstone",hard:3.5,tool:"Pioche",col:"#808080",tex:"https://minecraft.wiki/images/thumb/Dispenser_%28front%29_JE4.png/128px-Dispenser_%28front%29_JE4.png"},
    {id:"bookshelf",name:"Bibliothèque",cat:"decoration",hard:1.5,tool:"Hache",col:"#BC9458",tex:"https://minecraft.wiki/images/thumb/Bookshelf_JE4_BE4.png/128px-Bookshelf_JE4_BE4.png"},
    {id:"iron_bars",name:"Barreaux de Fer",cat:"building",hard:5,tool:"Pioche",col:"#A8A8A8",tex:"https://minecraft.wiki/images/thumb/Iron_Bars_JE4_BE5.png/128px-Iron_Bars_JE4_BE5.png"},
    {id:"sea_lantern",name:"Lanterne Marine",cat:"light",hard:0.3,tool:"Aucun",col:"#88CCFF",tex:"https://minecraft.wiki/images/thumb/Sea_Lantern_JE2_BE2.png/128px-Sea_Lantern_JE2_BE2.png"},
    {id:"magma_block",name:"Bloc de Magma",cat:"nether",hard:0.5,tool:"Aucun",col:"#8B2500",tex:"https://minecraft.wiki/images/thumb/Magma_Block_JE2_BE2.png/128px-Magma_Block_JE2_BE2.png"},
    {id:"nether_bricks",name:" Briques du Nether",cat:"nether",hard:2,tool:"Pioche",col:"#2C1218",tex:"https://minecraft.wiki/images/thumb/Nether_Bricks_JE3_BE2.png/128px-Nether_Bricks_JE3_BE2.png"},
    {id:"blackstone",name:"Pierre Noire",cat:"nether",hard:1.5,tool:"Pioche",col:"#2A2A2A",tex:"https://minecraft.wiki/images/thumb/Blackstone_JE1.png/128px-Blackstone_JE1.png"},
    {id:"basalt",name:"Basalte",cat:"nether",hard:1.25,tool:"Pioche",col:"#4A4A4A",tex:"https://minecraft.wiki/images/thumb/Basalt_%28vertical%29_JE1.png/128px-Basalt_%28vertical%29_JE1.png"},
    {id:"deepslate_bricks",name:" Briques Deepslate",cat:"building",hard:3.5,tool:"Pioche",col:"#4A4A4A",tex:"https://minecraft.wiki/images/thumb/Deepslate_Bricks_JE1.png/128px-Deepslate_Bricks_JE1.png"},
    {id:"copper_block",name:"Bloc de Cuivre",cat:"building",hard:3,tool:"Pioche Pierre",col:"#C07040",tex:"https://minecraft.wiki/images/thumb/Copper_Block_JE1.png/128px-Copper_Block_JE1.png"},
    {id:"moss_block",name:"Bloc de Mousse",cat:"nature",hard:0.1,tool:"Hache",col:"#5A7A3A",tex:"https://minecraft.wiki/images/thumb/Moss_Block_JE1.png/128px-Moss_Block_JE1.png"},
    {id:"tuff",name:"Tuff",cat:"nature",hard:1.5,tool:"Pioche",col:"#6A6A5A",tex:"https://minecraft.wiki/images/thumb/Tuff_JE1.png/128px-Tuff_JE1.png"},
    {id:"calcite",name:"Calcite",cat:"nature",hard:0.75,tool:"Pioche",col:"#DDDDCC",tex:"https://minecraft.wiki/images/thumb/Calcite_JE1.png/128px-Calcite_JE1.png"},
    {id:"ice",name:"Glace",cat:"nature",hard:0.5,tool:"Pioche",col:"#A0C8FF",tex:"https://minecraft.wiki/images/thumb/Ice_JE3_BE2.png/128px-Ice_JE3_BE2.png"},
    {id:"packed_ice",name:"Glace Compressée",cat:"nature",hard:0.5,tool:"Pioche",col:"#88B8FF",tex:"https://minecraft.wiki/images/thumb/Packed_Ice_JE3_BE2.png/128px-Packed_Ice_JE3_BE2.png"},
    {id:"blue_ice",name:"Glace Bleue",cat:"nature",hard:2.8,tool:"Pioche",col:"#5080FF",tex:"https://minecraft.wiki/images/thumb/Blue_Ice_JE2.png/128px-Blue_Ice_JE2.png"},
    {id:"snow_block",name:"Bloc de Neige",cat:"nature",hard:0.2,tool:"Pelle",col:"#F0F0F0",tex:"https://minecraft.wiki/images/thumb/Snow_Block_JE2.png/128px-Snow_Block_JE2.png"},
    {id:"prismarine",name:"Prismarine",cat:"building",hard:1.5,tool:"Pioche",col:"#6BA395",tex:"https://minecraft.wiki/images/thumb/Prismarine_JE2_BE2.png/128px-Prismarine_JE2_BE2.png"},
    {id:"dark_prismarine",name:"Prismarine Sombre",cat:"building",hard:1.5,tool:"Pioche",col:"#3A6A5A",tex:"https://minecraft.wiki/images/thumb/Dark_Prismarine_JE2.png/128px-Dark_Prismarine_JE2.png"},
    {id:"end_stone_bricks",name:" Briques de l'End",cat:"end",hard:3,tool:"Pioche",col:"#DBD6A0",tex:"https://minecraft.wiki/images/thumb/End_Stone_Bricks_JE3.png/128px-End_Stone_Bricks_JE3.png"},
    {id:"mud_bricks",name:" Briques de Boue",cat:"building",hard:1.5,tool:"Pioche",col:"#8A6A4C",tex:"https://minecraft.wiki/images/thumb/Mud_Bricks_JE1.png/128px-Mud_Bricks_JE1.png"},
    {id:"cherry_planks",name:"Planches de Cerisier",cat:"wood",hard:2,tool:"Hache",col:"#E8B4B8",tex:"https://minecraft.wiki/images/thumb/Cherry_Planks_JE1.png/128px-Cherry_Planks_JE1.png"},
    {id:"bamboo_planks",name:"Planches de Bambou",cat:"wood",hard:2,tool:"Hache",col:"#C8B862",tex:"https://minecraft.wiki/images/thumb/Bamboo_Planks_JE1.png/128px-Bamboo_Planks_JE1.png"},
  ],

  // ── ITEMS ──
  items: [
    {id:"diamond_sword",name:"Épée de Diamant",cat:"weapon",emoji:"⚔️"},
    {id:"diamond_pickaxe",name:"Pioche de Diamant",cat:"tool",emoji:"⛏️"},
    {id:"diamond_axe",name:"Hache de Diamant",cat:"tool",emoji:"🪓"},
    {id:"netherite_sword",name:"Épée de Netherite",cat:"weapon",emoji:"⚔️"},
    {id:"netherite_pickaxe",name:"Pioche de Netherite",cat:"tool",emoji:"⛏️"},
    {id:"bow",name:"Arc",cat:"weapon",emoji:"🏹"},
    {id:"crossbow",name:"Arbalète",cat:"weapon",emoji:"🏹"},
    {id:"trident",name:"Trident",cat:"weapon",emoji:"🔱"},
    {id:"mace",name:"Masse",cat:"weapon",emoji:"🔨"},
    {id:"shield",name:"Bouclier",cat:"armor",emoji:"🛡️"},
    {id:"elytra",name:"Élytres",cat:"tool",emoji:"🦋"},
    {id:"totem_of_undying",name:"Totem d'Immortalité",cat:"special",emoji:"🏅"},
    {id:"golden_apple",name:"Pomme Dorée",cat:"food",emoji:"🍎"},
    {id:"enchanted_golden_apple",name:"Pomme Dorée Enchantée",cat:"food",emoji:"🍎"},
    {id:"ender_pearl",name:"Perle de l'Ender",cat:"special",emoji:"🟣"},
    {id:"eye_of_ender",name:"Œil de l'Ender",cat:"special",emoji:"👁️"},
    {id:"blaze_rod",name:"Bâton de Blaze",cat:"material",emoji:"🔥"},
    {id:"nether_star",name:"Étoile du Nether",cat:"special",emoji:"⭐"},
    {id:"heart_of_the_sea",name:"Cœur de la Mer",cat:"special",emoji:"💙"},
    {id:"saddle",name:"Selle",cat:"tool",emoji:"🐴"},
    {id:"name_tag",name:"Étiquette",cat:"tool",emoji:"🏷️"},
    {id:"compass",name:"Boussole",cat:"tool",emoji:"🧭"},
    {id:"clock",name:"Horloge",cat:"tool",emoji:"🕐"},
    {id:"fishing_rod",name:"Canne à Pêche",cat:"tool",emoji:"🎣"},
    {id:"flint_and_steel",name:"Briquet",cat:"tool",emoji:"🔥"},
    {id:"bucket",name:"Seau",cat:"tool",emoji:"🪣"},
    {id:"water_bucket",name:"Seau d'Eau",cat:"tool",emoji:"🪣"},
    {id:"lava_bucket",name:"Seau de Lave",cat:"tool",emoji:"🪣"},
    {id:"experience_bottle",name:"Bouteille d'Enchantement",cat:"special",emoji:"🧪"},
    {id:"firework_rocket",name:"Fusée de Feu d'Artifice",cat:"special",emoji:"🎆"},
    {id:"spyglass",name:"Longue-vue",cat:"tool",emoji:"🔭"},
    {id:"enchanted_book",name:"Livre Enchanté",cat:"special",emoji:"📖"},
    {id:"goat_horn",name:"Corne de Chèvre",cat:"special",emoji:"📯"},
    {id:"wind_charge",name:"Charge de Vent",cat:"weapon",emoji:"💨"},
    {id:"trial_key",name:"Clé d'Épreuve",cat:"special",emoji:"🔑"},
    {id:"diamond_helmet",name:"Casque Diamant",cat:"armor",emoji:"⛑️"},
    {id:"diamond_chestplate",name:"Plastron Diamant",cat:"armor",emoji:"🦺"},
    {id:"diamond_leggings",name:"Jambières Diamant",cat:"armor",emoji:"👖"},
    {id:"diamond_boots",name:"Bottes Diamant",cat:"armor",emoji:"👢"},
    {id:"netherite_helmet",name:"Casque Netherite",cat:"armor",emoji:"⛑️"},
    {id:"netherite_chestplate",name:"Plastron Netherite",cat:"armor",emoji:"🦺"},
    {id:"cooked_beef",name:"Steak Cuit",cat:"food",emoji:"🥩"},
    {id:"bread",name:"Pain",cat:"food",emoji:"🍞"},
    {id:"golden_carrot",name:"Carotte Dorée",cat:"food",emoji:"🥕"},
  ],

  // ── MOBS ──
  mobs: [
    {id:"zombie",name:"Zombie",hp:20,emoji:"🧟",hostile:true,desc:"Brûle au soleil, drop de la chair pourrie"},
    {id:"skeleton",name:"Squelette",hp:20,emoji:"💀",hostile:true,desc:"Tire des flèches, brûle au soleil"},
    {id:"creeper",name:"Creeper",hp:20,emoji:"💚",hostile:true,desc:"Explose quand il est proche"},
    {id:"spider",name:"Araignée",hp:16,emoji:"🕷️",hostile:true,desc:"Neutre le jour, hostile la nuit"},
    {id:"enderman",name:"Enderman",hp:40,emoji:"🟣",hostile:false,desc:"Neutre, téléportation, ne pas regarder"},
    {id:"witch",name:"Sorcière",hp:26,emoji:"🧙",hostile:true,desc:"Lance des potions négatives"},
    {id:"zombie_villager",name:"Zombie Villageois",hp:20,emoji:"🧟",hostile:true,desc:"Peut être guéri avec une potion"},
    {id:"husk",name:"Husk",hp:20,emoji:"🧟",hostile:true,desc:"Zombie du désert, donne la Faim"},
    {id:"drowned",name:"Noyé",hp:20,emoji:"🧟",hostile:true,desc:"Zombie aquatique, peut drop un trident"},
    {id:"stray",name:"Stray",hp:20,emoji:"💀",hostile:true,desc:"Squelette de toundra, flèches de Lenteur"},
    {id:"blaze",name:"Blaze",hp:20,emoji:"🔥",hostile:true,desc:"Lance des boules de feu, drop Bâton de Blaze"},
    {id:"ghast",name:"Ghast",hp:10,emoji:"👻",hostile:true,desc:"Tire des boules de feu explosives"},
    {id:"wither_skeleton",name:"Squelette Wither",hp:20,emoji:"💀",hostile:true,desc:"Effet Wither, drop crâne rare"},
    {id:"piglin",name:"Piglin",hp:16,emoji:"🐷",hostile:false,desc:"Neutre, adore l'or, commerce"},
    {id:"piglin_brute",name:"Piglin Brutal",hp:50,emoji:"🐷",hostile:true,desc:"Toujours hostile, protège les bastions"},
    {id:"hoglin",name:"Hoglin",hp:40,emoji:"🐗",hostile:true,desc:"Charge, drop de la viande"},
    {id:"zoglin",name:"Zoglin",hp:40,emoji:"🐗",hostile:true,desc:"Hoglin zombie, tout attaque"},
    {id:"magma_cube",name:"Cube de Magma",hp:16,emoji:"🟧",hostile:true,desc:"Slime du Nether, immunisé à la lave"},
    {id:"slime",name:"Slime",hp:16,emoji:"🟢",hostile:true,desc:"Rebondit, se divise en petits slimes"},
    {id:"phantom",name:"Fantôme",hp:20,emoji:"👻",hostile:true,desc:"Attaque ceux qui ne dorment pas"},
    {id:"guardian",name:"Gardien",hp:30,emoji:"🐟",hostile:true,desc:"Laser, fatigue minière"},
    {id:"elder_guardian",name:"Ancien Gardien",hp:80,emoji:"🐟",hostile:true,desc:"Boss, fatigue minière permanente"},
    {id:"shulker",name:"Shulker",hp:30,emoji:"📦",hostile:true,desc:"Projets homing, lévitation"},
    {id:"vindicator",name:"Vindicateur",hp:24,emoji:"🪓",hostile:true,desc:"Attaque avec une hache"},
    {id:"pillager",name:"Pillard",hp:24,emoji:"🏹",hostile:true,desc:"Arbalète"},
    {id:"evoker",name:"Évocateur",hp:24,emoji:"🧙",hostile:true,desc:"Magie, invoque des Vex et des crocs"},
    {id:"ravager",name:"Ravageur",hp:100,emoji:"🐂",hostile:true,desc:"Très puissant, détruit les cultures"},
    {id:"vex",name:"Vex",hp:14,emoji:"👻",hostile:true,desc:"Traverse les murs"},
    {id:"warden",name:"Warden",hp:500,emoji:"🟫",hostile:true,desc:"Aveugle, 30 dégâts, ultra dangereux"},
    {id:"breeze",name:"Breeze",hp:30,emoji:"💨",hostile:true,desc:"Charges de vent"},
    {id:"bogged",name:"Ensablé",hp:20,emoji:"💀",hostile:true,desc:"Squelette avec poison"},
    {id:"armadillo",name:"Tatou",hp:12,emoji:"🦔",hostile:false,desc:"Drop des écailles pour armure de loup"},
    {id:"villager",name:"Villageois",hp:20,emoji:"👨‍🌾",hostile:false,desc:"Commerce, métiers variés"},
    {id:"wandering_trader",name:"Vagabond",hp:20,emoji:"🦙",hostile:false,desc:"Commerce d'objets rares"},
    {id:"iron_golem",name:"Golem de Fer",hp:100,emoji:"🤖",hostile:false,desc:"Protège les villageois"},
    {id:"snow_golem",name:"Golem de Neige",hp:4,emoji:"⛄",hostile:false,desc:"Lance des boules de neige"},
    {id:"wolf",name:"Loup",hp:8,emoji:"🐺",hostile:false,desc:"Apprivoisable, attaque les mobs"},
    {id:"cat",name:"Chat",hp:10,emoji:"🐱",hostile:false,desc:"Apprivoisable, effraie les creepers"},
    {id:"parrot",name:"Perroquet",hp:6,emoji:"🦜",hostile:false,desc:"Imite les sons des mobs"},
    {id:"dolphin",name:"Dauphin",hp:10,emoji:"🐬",hostile:false,desc:"Aide à trouver des trésors"},
    {id:"axolotl",name:"Axolotl",hp:14,emoji:"🦎",hostile:false,desc:"Attaque les mobs aquatiques"},
    {id:"frog",name:"Grenouille",hp:10,emoji:"🐸",hostile:false,desc:"Mange les slimes"},
    {id:"sniffer",name:"Sniffer",hp:14,emoji:"🦕",hostile:false,desc:"Fouille le sol pour des graines rares"},
    {id:"allay",name:"Allay",hp:20,emoji:"🧚",hostile:false,desc:"Collecte les items qui matchent"},
    {id:"cow",name:"Vache",hp:10,emoji:"🐄",hostile:false,desc:"Drop cuir, bœuf cru, seau de lait"},
    {id:"pig",name:"Cochon",hp:10,emoji:"🐷",hostile:false,desc:"Drop porc cru"},
    {id:"sheep",name:"Mouton",hp:10,emoji:"🐑",hostile:false,desc:"Drop laine, mouton cru"},
    {id:"chicken",name:"Poulet",hp:4,emoji:"🐔",hostile:false,desc:"Drop plumes, œufs, poulet cru"},
    {id:"horse",name:"Cheval",hp:30,emoji:"🐴",hostile:false,desc:"Montable, inventaire"},
    {id:"turtle",name:"Tortue",hp:30,emoji:"🐢",hostile:false,desc:"Pond des œufs, drop écailles"},
    {id:"bee",name:"Abeille",hp:10,emoji:"🐝",hostile:false,desc:"Pollinise, fabrique du miel"},
    {id:"wither",name:"Wither",hp:300,emoji:"💀",hostile:true,desc:"Boss, destruction massive"},
    {id:"ender_dragon",name:"Ender Dragon",hp:200,emoji:"🐉",hostile:true,desc:"Boss final du jeu"},
  ],

  // ── ENCHANTMENTS ──
  enchants: [
    {id:"sharpness",name:"Tranchant",max:5,desc:"Augmente les dégâts",type:"arme"},
    {id:"smite",name:"Smite",max:5,desc:"Dégâts aux morts-vivants",type:"arme"},
    {id:"efficiency",name:"Efficacité",max:5,desc:"Mine plus vite",type:"outil"},
    {id:"fortune",name:"Fortune",max:3,desc:"Plus de drops",type:"outil"},
    {id:"silk_touch",name:"Silk Touch",max:1,desc:"Récupère les blocs tels quels",type:"outil"},
    {id:"unbreaking",name:"Solidité",max:3,desc:"Durabilité augmentée",type:"tous"},
    {id:"mending",name:"Réparation",max:1,desc:"Répare avec l'XP",type:"tous"},
    {id:"protection",name:"Protection",max:4,desc:"Réduit tous les dégâts",type:"armure"},
    {id:"fire_protection",name:"Protection Feu",max:4,desc:"Réduit dégâts de feu",type:"armure"},
    {id:"blast_protection",name:"Protection Explosion",max:4,desc:"Réduit dégâts d'explosion",type:"armure"},
    {id:"projectile_protection",name:"Protection Projectile",max:4,desc:"Réduit dégâts de projectiles",type:"armure"},
    {id:"feather_falling",name:"Chute Amortie",max:4,desc:"Réduit dégâts de chute",type:"armure"},
    {id:"respiration",name:"Respiration",max:3,desc:"Respire sous l'eau",type:"armure"},
    {id:"aqua_affinity",name:"Aqua Affinity",max:1,desc:"Mine vite sous l'eau",type:"armure"},
    {id:"thorns",name:"Épineuses",max:3,desc:"Renvoie les dégâts",type:"armure"},
    {id:"depth_strider",name:"Depth Strider",max:3,desc:"Nage plus vite",type:"armure"},
    {id:"frost_walker",name:"Frost Walker",max:2,desc:"Gèle l'eau sous les pieds",type:"armure"},
    {id:"soul_speed",name:"Soul Speed",max:3,desc:"Rapide sur sable des âmes",type:"armure"},
    {id:"power",name:"Puissance",max:5,desc:"Plus de dégâts à l'arc",type:"arc"},
    {id:"punch",name:"Punch",max:2,desc:"Repousse avec l'arc",type:"arc"},
    {id:"flame",name:"Flamme",max:1,desc:"Flèches enflammées",type:"arc"},
    {id:"infinity",name:"Infinity",max:1,desc:"Flèches infinies",type:"arc"},
    {id:"looting",name:"Looting",max:3,desc:"Plus de drops de mobs",type:"arme"},
    {id:"fire_aspect",name:"Aspect Ardent",max:2,desc:"Met le feu",type:"arme"},
    {id:"knockback",name:"Knockback",max:2,desc:"Repousse les ennemis",type:"arme"},
    {id:"sweeping",name:"Sweeping Edge",max:3,desc:"Dégâts de zone",type:"arme"},
    {id:"loyalty",name:"Loyauté",max:3,desc:"Trident revient",type:"trident"},
    {id:"riptide",name:"Riptide",max:3,desc:"Propulsion dans l'eau/pluie",type:"trident"},
    {id:"channeling",name:"Channeling",max:1,desc:"Invoque la foudre",type:"trident"},
    {id:"impaling",name:"Impaling",max:5,desc:"Dégâts aux mobs aquatiques",type:"trident"},
    {id:"multishot",name:"Multishot",max:1,desc:"Tire 3 flèches",type:"arbalète"},
    {id:"quick_charge",name:"Quick Charge",max:3,desc:"Recharge plus vite",type:"arbalète"},
    {id:"piercing",name:"Piercing",max:4,desc:"Traverse les entités",type:"arbalète"},
    {id:"wind_burst",name:"Wind Burst",max:3,desc:"Explosion de vent (Masse)",type:"arme"},
    {id:"density",name:"Density",max:5,desc:"Dégâts en chute (Masse)",type:"arme"},
    {id:"breach",name:"Breach",max:4,desc:"Perce l'armure (Masse)",type:"arme"},
    {id:"vanishing_curse",name:"Curse of Vanishing",max:1,desc:"Disparaît à la mort",type:"malus"},
    {id:"binding_curse",name:"Curse of Binding",max:1,desc:"Ne peut pas être retiré",type:"malus"},
  ],

  // ── EFFECTS ──
  effects: [
    {id:"speed",name:"Vitesse",emoji:"💨",desc:"Augmente la vitesse de déplacement"},
    {id:"slowness",name:"Lenteur",emoji:"🐌",desc:"Réduit la vitesse"},
    {id:"haste",name:"Hâte",emoji:"⛏️",desc:"Mine plus vite"},
    {id:"mining_fatigue",name:"Fatigue Minière",emoji:"😴",desc:"Mine plus lentement"},
    {id:"strength",name:"Force",emoji:"💪",desc:"Augmente les dégâts"},
    {id:"instant_health",name:"Soin Instantané",emoji:"❤️",desc:"Restaure des PV"},
    {id:"instant_damage",name:"Dégât Instantané",emoji:"💀",desc:"Inflige des dégâts"},
    {id:"jump_boost",name:"Saut Amélioré",emoji:"🦘",desc:"Saute plus haut"},
    {id:"regeneration",name:"Régénération",emoji:"💖",desc:"Régénère les PV"},
    {id:"resistance",name:"Résistance",emoji:"🛡️",desc:"Réduit les dégâts"},
    {id:"fire_resistance",name:"Résistance au Feu",emoji:"🔥",desc:"Immunise au feu"},
    {id:"water_breathing",name:"Apnée",emoji:"🫁",desc:"Respire sous l'eau"},
    {id:"invisibility",name:"Invisibilité",emoji:"👻",desc:"Rend invisible"},
    {id:"night_vision",name:"Vision Nocturne",emoji:"🌙",desc:"Voit dans le noir"},
    {id:"poison",name:"Poison",emoji:"☠️",desc:"Inflige des dégâts sans tuer"},
    {id:"wither",name:"Wither",emoji:"💀",desc:"Dégâts continus"},
    {id:"absorption",name:"Absorption",emoji:"💛",desc:"PV bonus temporaires"},
    {id:"saturation",name:"Saturation",emoji:"🍽️",desc:"Restaure la faim"},
    {id:"levitation",name:"Lévitation",emoji:"🎈",desc:"Fait léviter"},
    {id:"slow_falling",name:"Chute Lente",emoji:"🪶",desc:"Tombe lentement"},
    {id:"luck",name:"Chance",emoji:"🍀",desc:"Meilleur loot"},
    {id:"bad_luck",name:"Malchance",emoji:"🍀",desc:"Mauvais loot"},
    {id:"dolphins_grace",name:"Grâce du Dauphin",emoji:"🐬",desc:"Nage très vite"},
    {id:"conduit_power",name:"Pouvoir du Conduit",emoji:"🌊",desc:"Mine vite sous l'eau"},
    {id:"darkness",name:"Obscurité",emoji:"🌑",desc:"Assombrit l'écran (Warden)"},
  ],

  // ── STRUCTURES IN-GAME ──
  structures: [
    {name:"Village",desc:"Villages de villageois avec maisons, fermes et marchands",biome:"Plaine, Savane, Taïga, Désert"},
    {name:"Donjon",desc:"Salle souterraine avec spawner de mob et coffres",biome:"Souterrain"},
    {name:"Temple du Désert",desc:"Temple de sable avec pièges à TNT",biome:"Désert"},
    {name:"Temple de la Jungle",desc:"Temple végétal avec pièges à flèches",biome:"Jungle"},
    {name:"Manoir Woodland",desc:"Gigantesque manoir avec pillagers",biome:"Forêt Sombre"},
    {name:"Monument Océanique",desc:"Monument sous-marin avec guardians",biome:"Océan Profond"},
    {name:"Forteresse du Nether",desc:"Structure du Nether avec blazes",biome:"Nether"},
    {name:"Cité de l'End",desc:"Ville de l'End avec shulkers et élytres",biome:"End"},
    {name:"Tour de Pillage",desc:"Tour des pillagers",biome:"Plaine, Taïga"},
    {name:"Bastion",desc:"Rempart du Nether avec piglins brutaux",biome:"Nether"},
    {name:"Ruines Océaniques",desc:"Ruines sous-marines",biome:"Océan"},
    {name:"Épave",desc:"Navires échoués avec coffres",biome:"Océan"},
    {name:"Ancienne Cité",desc:"Cité sculk avec le Warden",biome:"Deep Dark"},
    {name:"Salle d'Épreuve",desc:"Structure avec Trial Spawner",biome:"Overworld"},
  ],

  // ── COMMANDS ──
  commands: [
    {cmd:"give",syntax:"/give <cible> <item> [quantité]",desc:"Donne un item",ex:"/give @s diamond 64"},
    {cmd:"tp",syntax:"/tp <cible> <x> <y> <z>",desc:"Téléporte",ex:"/tp @s 0 100 0"},
    {cmd:"effect",syntax:"/effect give <cible> <effet> [durée] [niv]",desc:"Applique un effet",ex:"/effect give @s speed 60 2"},
    {cmd:"gamemode",syntax:"/gamemode <mode> [cible]",desc:"Change mode de jeu",ex:"/gamemode creative"},
    {cmd:"difficulty",syntax:"/difficulty <difficulté>",desc:"Change la difficulté",ex:"/difficulty peaceful"},
    {cmd:"time",syntax:"/time set <valeur>",desc:"Change l'heure",ex:"/time set day"},
    {cmd:"weather",syntax:"/weather <météo>",desc:"Change la météo",ex:"/weather clear"},
    {cmd:"fill",syntax:"/fill <from> <to> <bloc>",desc:"Remplit une zone",ex:"/fill ~ ~ ~ ~10 ~5 ~10 stone hollow"},
    {cmd:"clone",syntax:"/clone <from> <to> <dest>",desc:"Copie une structure",ex:"/clone 0 0 0 10 10 10 100 0 0"},
    {cmd:"setblock",syntax:"/setblock <pos> <bloc>",desc:"Place un bloc",ex:"/setblock ~ ~ ~ diamond_block"},
    {cmd:"summon",syntax:"/summon <entité> [pos]",desc:"Invoque une entité",ex:"/summon zombie ~ ~ ~"},
    {cmd:"kill",syntax:"/kill [cible]",desc:"Tue une entité",ex:"/kill @e[type=zombie]"},
    {cmd:"clear",syntax:"/clear [cible] [item]",desc:"Vide l'inventaire",ex:"/clear @s"},
    {cmd:"enchant",syntax:"/enchant <cible> <enchant> [niv]",desc:"Enchante l'item en main",ex:"/enchant @s sharpness 5"},
    {cmd:"xp",syntax:"/xp <amount> [cible]",desc:"Donne de l'XP",ex:"/xp 1000L @s"},
    {cmd:"gamerule",syntax:"/gamerule <règle> [valeur]",desc:"Change une règle",ex:"/gamerule keepInventory true"},
    {cmd:"title",syntax:"/title <cible> title <texte>",desc:"Affiche un titre",ex:"/title @s title Hello"},
    {cmd:"say",syntax:"/say <message>",desc:"Message global",ex:"/say Bonjour !"},
    {cmd:"execute",syntax:"/execute <args> run <cmd>",desc:"Exécute conditionnel",ex:"/execute as @a run say hi"},
    {cmd:"particle",syntax:"/particle <type> <pos>",desc:"Crée des particules",ex:"/particle flame ~ ~ ~ 1 1 1 0.1 100"},
    {cmd:"playsound",syntax:"/playsound <son> <cible>",desc:"Joue un son",ex:"/playsound entity.experience_orb.pickup master @s"},
    {cmd:"locate",syntax:"/locate structure <type>",desc:"Trouve une structure",ex:"/locate structure village"},
    {cmd:"spawnpoint",syntax:"/spawnpoint [cible] [pos]",desc:"Set le spawnpoint",ex:"/spawnpoint @s"},
    {cmd:"attribute",syntax:"/attribute <cible> <attr> <action>",desc:"Modifie un attribut",ex:"/attribute @s generic.max_health base set 40"},
    {cmd:"item",syntax:"/item replace <slot> with <item>",desc:"Remplace un item",ex:"/item replace entity @s weapon with diamond_sword"},
    {cmd:"data",syntax:"/data merge entity <cible> <nbt>",desc:"Modifie les NBT",ex:"/data merge entity @e[type=zombie,limit=1] {CustomName:\"Boss\"}"},
    {cmd:"worldborder",syntax:"/worldborder set <taille>",desc:"Taille du monde",ex:"/worldborder set 1000"},
    {cmd:"bossbar",syntax:"/bossbar add <id> <nom>",desc:"Crée une barre de boss",ex:"/bossbar add mybar \"Mon Boss\""},
    {cmd:"tag",syntax:"/tag <cible> add <tag>",desc:"Ajoute un tag",ex:"/tag @s add admin"},
    {cmd:"scoreboard",syntax:"/scoreboard objectives add <nom> <critère>",desc:"Crée un objectif",ex:"/scoreboard objectives add kills playerKillCount"},
    {cmd:"team",syntax:"/team add <nom>",desc:"Crée une équipe",ex:"/team add rouge"},
    {cmd:"teleport",syntax:"/tp @s <pos> [rotation]",desc:"TP avec rotation",ex:"/tp @s 0 100 0 0 90"},
    {cmd:"spreadplayers",syntax:"/spreadplayers <pos> <spread> <range> @a",desc:"Disperse les joueurs",ex:"/spreadplayers 0 0 10 500 @a"},
    {cmd:"recipe",syntax:"/recipe give @s *",desc:"Débloque toutes les recettes",ex:"/recipe give @s *"},
    {cmd:"advancement",syntax:"/advancement grant @s everything",desc:"Donne tous les avancements",ex:"/advancement grant @s everything"},
    {cmd:"ride",syntax:"/ride <cible> mount <monture>",desc:"Fait monter",ex:"/ride @s mount @e[type=horse,limit=1]"},
    {cmd:"damage",syntax:"/damage <cible> <amount> [type]",desc:"Inflige des dégâts",ex:"/damage @s 10 minecraft:fall"},
    {cmd:"forceload",syntax:"/forceload add <pos>",desc:"Force chargement chunk",ex:"/forceload add ~ ~"},
    {cmd:"setworldspawn",syntax:"/setworldspawn [pos]",desc:"Spawn du monde",ex:"/setworldspawn 0 100 0"},
  ],
};

// ── GENERATED STRUCTURES ──
const BUILDS = {
  mcdonalds: {
    name:"McDonald's", emoji:"🍔", desc:"Restaurant fast-food avec cuisine, comptoir, salle, arches dorées",
    w:21, h:12, d:16,
    materials:{white_concrete:450,red_concrete:280,yellow_concrete:120,gray_concrete:200,glass:85,oak_planks:180,smooth_stone:320,stone_bricks:150,glowstone:24,lit_redstone_lamp:10,oak_fence:40,quartz_block:90,iron_bars:30,black_concrete:40},
    steps:[
      {t:"Fondations",d:"Zone 21×16, sol en smooth_stone, entrée sud 6 blocs",b:{smooth_stone:320}},
      {t:"Murs extérieurs",d:"Murs 6 blocs haut, white_concrete partout, red_concrete façade avant. Ouvertures fenêtres 3×3",b:{white_concrete:380,red_concrete:200}},
      {t:"Fenêtres & portes",d:"glass dans ouvertures, 4 entrées, iron_bars déco",b:{glass:85,iron_bars:30}},
      {t:"Toit plat",d:"quartz_block sur toute la surface + bordure red_concrete, débord 1 bloc",b:{quartz_block:90,red_concrete:80}},
      {t:"Arches dorées M",d:"yellow_concrete, forme M sur façade: 4 blocs haut, 6 de large",b:{yellow_concrete:120}},
      {t:"Cuisine",d:"Furnace=grill, crafting_table=plans de travail, barrel=stockage",b:{smooth_stone:80,crafting_table:6,furnace:8,barrel:12}},
      {t:"Comptoir",d:"stone_bricks + glowstone au plafond",b:{stone_bricks:150,glowstone:24}},
      {t:"Salle",d:"Tables en oak_planks + oak_stairs, carpets rouge/blanc, lanternes",b:{oak_planks:180,oak_fence:40,lit_redstone_lamp:10}},
      {t:"Signalétique",d:"Bannières jaune/rouge + panneaux",b:{yellow_concrete:20}},
      {t:"Parking & extérieur",d:"gray_concrete sol, arbres, poubelles barrel",b:{gray_concrete:200,barrel:4}},
    ],
    tips:["Les arches M jaunes = détail iconique","Glowstone cachée dans plafond pour éclairage","Sol cuisine en smooth_stone","Panneaux avec texte 'McDonald's'","N'oublie pas les toilettes à l'arrière","Avec des friends: faites les repas en RP!"]
  },
  castle: {
    name:"Château Fort", emoji:"🏰", desc:"Château médiéval complet: donjon, tours, douves, pont-levis, grande salle",
    w:32, h:25, d:32,
    materials:{stone_bricks:2800,cobblestone:1200,mossy_stone_bricks:400,oak_planks:600,oak_log:300,iron_bars:80,torch:60,lantern:20,glass:45,oak_fence:200,oak_stairs:200,oak_slab:150,red_banner:16,chest:16,bookshelf:24,anvil:2,enchanting_table:1,bed:8,armor_stand:6,painting:12,ladder:100,chain:40,barrel:10},
    steps:[
      {t:"Douves & fondations",d:"Creuse 3 prof, 4 large autour 32×32. Stone_bricks fondations. Remplis d'eau",b:{stone_bricks:400}},
      {t:"Murailles",d:"Murs 10 blocs haut stone_bricks + cobblestone. Chemin de ronde en haut",b:{stone_bricks:1600,cobblestone:800}},
      {t:"4 Tours d'angle",d:"Tours circulaires ø7, h18. Meurtrières 1×2",b:{stone_bricks:800,mossy_stone_bricks:400}},
      {t:"Porte & pont-levis",d:"Arc monumental, pont-levis oak_planks + chain, lourdes portes",b:{oak_planks:200,chain:40,cobblestone:200}},
      {t:"Donjon central",d:"10×10, h20, dépasse murailles. Toit conique. Bannières royales",b:{stone_bricks:600,oak_stairs:100,red_banner:16}},
      {t:"Plan intérieur",d:"Planchers oak_planks, poutres oak_log, division en salles",b:{oak_planks:400,oak_log:300}},
      {t:"Grande salle",d:"Table banquet, cheminée, trophées armor_stand, peintures",b:{armor_stand:6,painting:12,oak_fence:200}},
      {t:"Bibliothèque & alchimie",d:"bookshelf, enchanting_table, brewing_stand",b:{bookshelf:24,enchanting_table:1}},
      {t:"Chambres & armurerie",d:"Beds, chests, anvil, barrel, racks d'armes",b:{bed:8,chest:16,anvil:2,barrel:10}},
      {t:"Éclairage & finitions",d:"Torches, lanternes, drapeaux tours, ladder colimaçon",b:{torch:60,lantern:20,ladder:100}},
    ],
    tips:["Varie stone_bricks / cobblestone / mossy pour réalisme","Tours circulaires > carrées","Mossy = vieillissement naturel","Pont-levis + douves = impression garanti","Meurtrières = fentes 1×2 avec verre","Donjon = point le plus haut"]
  },
  skyscraper: {
    name:"Gratte-ciel", emoji:"🏙️", desc:"Immeuble moderne 20 étages avec façade vitrée, hall, rooftop",
    w:20, h:40, d:20,
    materials:{white_concrete:3200,gray_concrete:1600,glass:800,quartz_block:300,smooth_stone:400,iron_block:200,glowstone:100,lit_redstone_lamp:60,black_concrete:100,sea_lantern:30,iron_bars:100,oak_planks:200,redstone:100,redstone_block:20,lever:20},
    steps:[
      {t:"Fondations profondes",d:"iron_block + gray_concrete, parking souterrain 3 blocs",b:{iron_block:200,gray_concrete:400}},
      {t:"Structure métallique",d:"iron_block coins, gray_concrete noyau central (escaliers/ascenseur)",b:{gray_concrete:800}},
      {t:"Façade 1-10",d:"Alternance glass/white_concrete bandes 2 dalles",b:{glass:400,white_concrete:1600}},
      {t:"Façade 11-20",d:"Plus de verre, léger retrait pour effet hauteur",b:{glass:400,white_concrete:1600}},
      {t:"Hall d'accueil",d:"Sol quartz_block, accueil smooth_stone, sea_lantern, portes vitrées",b:{quartz_block:200,smooth_stone:200,sea_lantern:20}},
      {t:"Escaliers & noyau",d:"Escalier spirale quartz, noyau ascenseur",b:{quartz_block:100,smooth_stone:200}},
      {t:"Aménagement étages",d:"Open space oak_planks, chest casiers, barrel",b:{oak_planks:200,chest:20,barrel:10}},
      {t:"Éclairage LED",d:"redstone_lamp encastrées plafond, redstone + lever",b:{lit_redstone_lamp:60,glowstone:100,redstone:100}},
      {t:"Rooftop",d:"black_concrete, bancs, jardin grass_block, héliport",b:{black_concrete:100,iron_block:100}},
      {t:"Finitions extérieures",d:"Éclairage nuit sea_lantern cachées, nom en blocs, détails métal",b:{sea_lantern:10,iron_bars:100}},
    ],
    tips:["Verre teinté bleu clair = look moderne","Béton blanc = rendu propre","Éclairage nuit avec blocs cachés","Ascenseur piston/redstone fonctionnel","Rooftop avec jardin = must","Varie textures façade pour éviter monotonie"]
  },
  treehouse: {
    name:"Cabane dans l'Arbre", emoji:"🌳", desc:"Maison dans un arbre géant avec plateformes, ponts suspendus, toboggan",
    w:25, h:30, d:25,
    materials:{oak_log:800,spruce_log:400,oak_planks:600,spruce_planks:300,oak_leaves:2000,oak_fence:300,oak_stairs:200,ladder:150,torch:30,lantern:20,glass:40,chest:20,crafting_table:4,furnace:4,bed:4,barrel:10,painting:8,chain:20,campfire:4,moss_carpet:20},
    steps:[
      {t:"Méga-tronc 3×3",d:"oak_log ×3×3 sur 20 blocs haut. Racines à la base",b:{oak_log:400}},
      {t:"Branches principales",d:"4-5 branches 8-12 blocs long en spruce_log",b:{spruce_log:400,oak_log:200}},
      {t:"Plateforme vie (Y12)",d:"Sol oak_planks, garde-corps oak_fence",b:{oak_planks:300,oak_fence:100}},
      {t:"Chambres (Y18)",d:"2-3 pièces spruce_planks, fenêtres glass, beds",b:{spruce_planks:200,glass:40,bed:4}},
      {t:"Observatoire sommet",d:"Vue dégagée, garde-corps, dôme oak_stairs",b:{oak_stairs:100,oak_fence:100}},
      {t:"Ponts suspendus",d:"Relient plateformes, oak_planks + oak_fence + chain",b:{oak_planks:200,oak_fence:100,chain:20}},
      {t:"Escaliers spirale",d:"ladder autour du tronc + oak_stairs + trapdoors",b:{ladder:150,oak_stairs:100}},
      {t:"Aménagement",d:"Tables, chest, furnace, carpet, painting",b:{chest:20,crafting_table:4,furnace:4,painting:8,barrel:10}},
      {t:"Feuillage",d:"oak_leaves ×2000 partout. Vines + moss_carpet + fleurs",b:{oak_leaves:2000,moss_carpet:20}},
      {t:"Éclairage",d:"Lanternes dans feuilles, torche, campfire au sol",b:{lantern:20,torch:30,campfire:4}},
    ],
    tips:["Commence par tronc → branches → feuillage","2 types de bois (oak + spruce) = variété","Ponts avec chaînes = effet génial","Cache éclairage dans feuilles = magique la nuit","Campfire au pied = ambiance parfaite","Toboggan avec water + soul_sand !"]
  },
  pirate_ship: {
    name:"Bateau Pirate", emoji:"🏴‍☠️", desc:"Navire pirate détaillé: ponts, cabine capitaine, canons, mâture",
    w:12, h:18, d:30,
    materials:{dark_oak_planks:800,spruce_planks:400,oak_planks:300,spruce_log:200,oak_fence:200,oak_stairs:150,white_wool:100,black_wool:40,red_wool:30,chain:60,glass:10,chest:12,barrel:16,torch:10,lantern:8,ladder:40,dispenser:8,tnt:16,red_banner:8,anvil:1,bed:2},
    steps:[
      {t:"Coque",d:"Forme navire dark_oak_planks: étroite bas, large milieu, pointe proue",b:{dark_oak_planks:600}},
      {t:"Pont principal",d:"oak_planks, garde-corps oak_fence tout autour",b:{oak_planks:200,oak_fence:150}},
      {t:"Cabine capitaine",d:"Arrière spruce_planks, fenêtre glass, porte",b:{spruce_planks:200,glass:10}},
      {t:"Mât principal",d:"spruce_log 15 blocs haut, vergues en oak_slab",b:{spruce_log:100}},
      {t:"Voiles",d:"white_wool triangles. Jolly Roger black_wool + red_wool",b:{white_wool:100,black_wool:40,red_wool:30}},
      {t:"Proue",d:"Figure de proue, oak_stairs courbes, balcon capitaine",b:{oak_stairs:100,dark_oak_planks:100}},
      {t:"Canons",d:"Dispensers sur côtés, ouvertures coque, tnt munitions",b:{dispenser:8,tnt:16}},
      {t:"Intérieur",d:"Cabine: bed+chest+anvil. Cale: barrel+chest. Cuisine: furnace",b:{chest:12,barrel:16,bed:2,anvil:1}},
      {t:"Accès",d:"Ladder pour monter aux mâts, capot cale oak_stairs",b:{ladder:40,oak_stairs:50}},
      {t:"Drapeaux & finitions",d:"Bannière pirate sommet, lanternes, barils pont",b:{lantern:8,red_banner:8,oak_fence:50}},
    ],
    tips:["Forme coque = commence par profil latéral","oak_stairs pour courbes réalistes","Voiles asymétriques = effet vent","Canons = dispensers + TNT fonctionnent !","Drapeau pirate au sommet = caractère","Placer sur l'eau = spectaculaire"]
  },
  volcano_lair: {
    name:"Base Volcanique Secrète", emoji:"🌋", desc:"Base secrète dans un volcan: laboratoire, hangar, salle de contrôle",
    w:30, h:25, d:30,
    materials:{blackstone:2000,basalt:1500,deepslate_bricks:600,magma_block:200,redstone_lamp:80,iron_block:300,obsidian:400,glass:100,iron_bars:80,lit_redstone_lamp:40,redstone:200,redstone_block:30,piston:30,hopper:30,chest:30,barrel:20,crafting_table:6,furnace:10,anvil:3,enchanting_table:2,beacon:2,white_concrete:200,gray_concrete:300,black_concrete:100,end_rod:30,sea_lantern:20},
    steps:[
      {t:"Volcan extérieur",d:"Montagne blackstone + basalt. Cratère au sommet. Base 30×30",b:{blackstone:2000,basalt:1500}},
      {t:"Cratère & lave",d:"Lave dans cratère. magma_block autour pour effet chaleur",b:{magma_block:200}},
      {t:"Entrée secrète",d:"Entrée cachée avec piston+redstone. Invisible de l'extérieur",b:{piston:30,redstone:100}},
      {t:"Hall principal",d:"Grand hall deepslate_bricks, sol basalt, éclairage dramatique",b:{deepslate_bricks:600,end_rod:30}},
      {t:"Laboratoire",d:"Brewing_stand, enchanting_table, tables craft. Murs blancs, éclairage intense",b:{white_concrete:200,sea_lantern:20,enchanting_table:2}},
      {t:"Salle de contrôle",d:"Cibles (target) = boutons, glass = écrans, systèmes redstone",b:{glass:100,redstone:100,redstone_block:30}},
      {t:"Hangar véhicules",d:"Grand hangar, porte auto pistons, sol iron_block",b:{iron_block:300,iron_bars:80}},
      {t:"Arsenal & stockage",d:"Anvil, smithing_table, grindstone. Chest+barrel massif",b:{anvil:3,chest:30,barrel:20,hopper:30}},
      {t:"Quartiers",d:"Lits, déco sombre, salle briefing lectern, obsidian murs",b:{obsidian:400,gray_concrete:300,black_concrete:100}},
      {t:"Éclairage & systèmes",d:"redstone_lamp, glowstone, beacons, alarmes, sécurité",b:{lit_redstone_lamp:80,beacon:2,dispenser:10}},
    ],
    tips:["Entrée secrète piston = détail satisfaisant","Magma + lave = effet volcanique réalist","Contraste noir/rouge = ambiance villain","Beacons avec effets au labo","Cache éclairage derrière blocs = dramatique","Ajoute un escape pod secret !"]
  },
  futuristic_house: {
    name:"Maison Futuriste", emoji:"🏠", desc:"Maison futuriste avec piscine, jardin toit, garage, domotique",
    w:18, h:12, d:22,
    materials:{white_concrete:600,black_concrete:300,glass:200,gray_concrete:200,quartz_block:400,smooth_stone:300,iron_block:100,glowstone:40,sea_lantern:30,lit_redstone_lamp:50,redstone:150,piston:15,oak_planks:100,spruce_planks:100,prismarine:50,dark_prismarine:30,iron_bars:60,end_rod:40,grass_block:40,iron_bars:60},
    steps:[
      {t:"Fondations",d:"quartz_block, architecture en L (2 étages + 1 étage)",b:{quartz_block:400,gray_concrete:200}},
      {t:"Murs extérieurs",d:"white_concrete surfaces, black_concrete accents. Minimaliste",b:{white_concrete:600,black_concrete:300}},
      {t:"Façade vitrée",d:"Grandes baies glass. Façade sud presque toute vitrée",b:{glass:200,iron_bars:60}},
      {t:"RDC intérieur",d:"Open space cuisine/salon, sol smooth_stone, îlot quartz",b:{smooth_stone:200,quartz_block:200}},
      {t:"Étage",d:"Chambres + bureau. Escalier quartz. Planchers bois",b:{oak_planks:100,spruce_planks:100,quartz_block:100}},
      {t:"Piscine",d:"prismarine + water. Terrasse smooth_stone",b:{prismarine:50,dark_prismarine:30,smooth_stone:100}},
      {t:"Jardin toit",d:"grass_block, saplings, flowers. Garde-corps iron_block",b:{grass_block:40,iron_block:100}},
      {t:"Garage",d:"Porte auto pistons, sol gray_concrete",b:{gray_concrete:100,piston:15}},
      {t:"Domotique",d:"Éclairage auto redstone_lamp + observer. Portes auto",b:{lit_redstone_lamp:50,end_rod:40,sea_lantern:30,redstone:150}},
      {t:"Décoration",d:"Tapis blanc/bleu clair, déco min, éclairage amb",b:{glowstone:40}},
    ],
    tips:["Style = géométrie simple + blanc/noir","Grandes baies = essentiel futuriste","Piscine prismarine = rendu incroyable","Jardin toit = tendance + fonctionnel","Domotique redstone = interactive","end_rod = éclairage moderne épuré"]
  },
  church: {
    name:"Église", emoji:"⛪", desc:"Église médiévale: clocher, nef, chœur, vitraux, crypte",
    w:16, h:22, d:28,
    materials:{stone_bricks:2000,cobblestone:800,mossy_stone_bricks:200,oak_planks:400,oak_log:200,glass:195,oak_fence:100,oak_stairs:150,oak_slab:100,quartz_block:200,smooth_stone:150,torch:30,lantern:15,bookshelf:30,chest:8,barrel:6,painting:10,red_banner:12,ladder:40,chain:20,spruce_planks:100},
    steps:[
      {t:"Fondations & nef",d:"Croix latine 16×28. Nef centrale 8, bas-côtés 4 chacun",b:{stone_bricks:400}},
      {t:"Murs nef",d:"Murs 10 haut. Colonnes quartz_block. Arcades stone_bricks",b:{stone_bricks:1200,quartz_block:200}},
      {t:"Vitraux",d:"Verre coloré: blanc, bleu, rouge, jaune, vert, violet. Rosace façade ouest",b:{glass:195}},
      {t:"Chœur & abside",d:"Abside semi-circ. Sol quartz_block. Autel smooth_stone + quartz",b:{quartz_block:100,smooth_stone:150,stone_bricks:400}},
      {t:"Clocher",d:"Tour carrée au-dessus façade, toit pointu oak_stairs. Bell",b:{stone_bricks:400,oak_stairs:100,cobblestone:200}},
      {t:"Charpente",d:"Charpente apparente oak_log + oak_planks. Voûte berceau",b:{oak_log:200,oak_planks:200,oak_stairs:50}},
      {t:"Mobilier liturgique",d:"Bancs oak_fence+oak_slab, ambon lectern, chandeliers",b:{oak_fence:100,oak_slab:100}},
      {t:"Sacristie & crypte",d:"bookshelf, chest sous le chœur. stone_bricks",b:{bookshelf:30,chest:8,cobblestone:400,spruce_planks:100}},
      {t:"Art sacré",d:"Peintures, bannières, statues armor_stand, flower_pot",b:{painting:10,red_banner:12}},
      {t:"Éclairage ambiant",d:"Lanternes, torches. Lumière tamisée. Vitraux illuminés",b:{lantern:15,torch:30}},
    ],
    tips:["Vitraux colorés = détail le plus impressionnant","Colonnes intérieures = majesté","Charpente apparente bois = caractère","Clocher = point le plus visible","Éclairage tamisé + bougies = atmosphère","Crypte sous église = mystère + espace"]
  }
};