// MeinkraftAI — Block Database (colors for 3D rendering)
const BLOCKS = {
  // id: {name, col (hex color), cat}
  stone:{n:"Pierre",c:"#808080",cat:"b"},
  granite:{n:"Granite",c:"#9A6C50",cat:"b"},
  diorite:{n:"Diorite",c:"#C8C8C8",cat:"b"},
  andesite:{n:"Andésite",c:"#888888",cat:"b"},
  grass_block:{n:"Herbe",c:"#5D8C3E",cat:"n"},
  dirt:{n:"Terre",c:"#8B6F47",cat:"n"},
  cobblestone:{n:"Pierres",c:"#777777",cat:"b"},
  oak_planks:{n:"Pl. Chêne",c:"#BC9458",cat:"w"},
  spruce_planks:{n:"Pl. Épicéa",c:"#6B4F2A",cat:"w"},
  birch_planks:{n:"Pl. Bouleau",c:"#D4C483",cat:"w"},
  jungle_planks:{n:"Pl. Jungle",c:"#9A6C3E",cat:"w"},
  acacia_planks:{n:"Pl. Acacia",c:"#AD5E24",cat:"w"},
  dark_oak_planks:{n:"Pl. Chêne Noir",c:"#3E2812",cat:"w"},
  cherry_planks:{n:"Pl. Cerisier",c:"#E8B4B8",cat:"w"},
  bamboo_planks:{n:"Pl. Bambou",c:"#C8B862",cat:"w"},
  oak_log:{n:"Bûche Chêne",c:"#6B511F",cat:"w"},
  spruce_log:{n:"Bûche Épicéa",c:"#3E2812",cat:"w"},
  oak_wood:{n:"Bois Chêne",c:"#BC9458",cat:"w"},
  bedrock:{n:"Bedrock",c:"#333333",cat:"n"},
  sand:{n:"Sable",c:"#DBD3A0",cat:"n"},
  red_sand:{n:"Sable Rouge",c:"#C0722E",cat:"n"},
  gravel:{n:"Gravier",c:"#888078",cat:"n"},
  gold_ore:{n:"Or",c:"#FCDB5C",cat:"o"},
  iron_ore:{n:"Fer",c:"#D8AF93",cat:"o"},
  coal_ore:{n:"Charbon",c:"#2A2A2A",cat:"o"},
  diamond_ore:{n:"Diamant",c:"#5CE5E5",cat:"o"},
  emerald_ore:{n:"Émeraude",c:"#17DD62",cat:"o"},
  redstone_ore:{n:"Redstone",c:"#FF0000",cat:"o"},
  lapis_ore:{n:"Lapis",c:"#1A3C8C",cat:"o"},
  copper_ore:{n:"Cuivre",c:"#C07040",cat:"o"},
  gold_block:{n:"Bloc Or",c:"#FCDB5C",cat:"m"},
  iron_block:{n:"Bloc Fer",c:"#D8D8D8",cat:"m"},
  diamond_block:{n:"Bloc Diamant",c:"#5CE5E5",cat:"m"},
  emerald_block:{n:"Bloc Émeraude",c:"#17DD62",cat:"m"},
  redstone_block:{n:"Bloc Redstone",c:"#FF0000",cat:"m"},
  netherite_block:{n:"Bloc Netherite",c:"#4A3A3A",cat:"m"},
  lapis_block:{n:"Bloc Lapis",c:"#1A3C8C",cat:"m"},
  copper_block:{n:"Bloc Cuivre",c:"#C07040",cat:"m"},
  coal_block:{n:"Bloc Charbon",c:"#2A2A2A",cat:"m"},
  glass:{n:"Verre",c:"#C8E8FF",cat:"d"},
  glass_pane:{n:"Vitre",c:"#C8E8FF",cat:"d"},
  bricks:{n:"Briques",c:"#9B4C3C",cat:"b"},
  stone_bricks:{n:"P. Taillées",c:"#7A7A7A",cat:"b"},
  mossy_stone_bricks:{n:"P.T. Moussues",c:"#6A7A5A",cat:"b"},
  obsidian:{n:"Obsidienne",c:"#1B0B2A",cat:"n"},
  netherrack:{n:"Netherrack",c:"#6A1A1A",cat:"ne"},
  soul_sand:{n:"Sable Âmes",c:"#5A4A2A",cat:"ne"},
  glowstone:{n:"P. Luminescente",c:"#FFD700",cat:"l"},
  end_stone:{n:"Pierre End",c:"#DBD6A0",cat:"e"},
  purpur_block:{n:"Purpur",c:"#9A5A9A",cat:"e"},
  quartz_block:{n:"Quartz",c:"#E8E4D8",cat:"b"},
  smooth_stone:{n:"P. Lisse",c:"#A0A0A0",cat:"b"},
  sandstone:{n:"Grès",c:"#DBD3A0",cat:"b"},
  terracotta:{n:"Terre Cuite",c:"#985B43",cat:"b"},
  white_concrete:{n:"Béton Blanc",c:"#CFD5D6",cat:"b"},
  black_concrete:{n:"Béton Noir",c:"#080A0F",cat:"b"},
  red_concrete:{n:"Béton Rouge",c:"#8E2121",cat:"b"},
  blue_concrete:{n:"Béton Bleu",c:"#2C2E8F",cat:"b"},
  yellow_concrete:{n:"Béton Jaune",c:"#F1AF15",cat:"b"},
  gray_concrete:{n:"Béton Gris",c:"#36393D",cat:"b"},
  green_concrete:{n:"Béton Vert",c:"#3C4514",cat:"b"},
  orange_concrete:{n:"Béton Orange",c:"#E06100",cat:"b"},
  light_blue_concrete:{n:"B. Bleu Clair",c:"#2489C7",cat:"b"},
  white_wool:{n:"Laine Blanche",c:"#F9FFFE",cat:"d"},
  red_wool:{n:"Laine Rouge",c:"#B02E26",cat:"d"},
  black_wool:{n:"Laine Noire",c:"#1D1D21",cat:"d"},
  blue_wool:{n:"Laine Bleue",c:"#3C44AA",cat:"d"},
  yellow_wool:{n:"Laine Jaune",c:"#FED83D",cat:"d"},
  green_wool:{n:"Laine Verte",c:"#5B7C16",cat:"d"},
  orange_wool:{n:"Laine Orange",c:"#F9801D",cat:"d"},
  white_carpet:{n:"Tapis Blanc",c:"#F9FFFE",cat:"d"},
  red_carpet:{n:"Tapis Rouge",c:"#B02E26",cat:"d"},
  crafting_table:{n:"Établi",c:"#BC9458",cat:"u"},
  furnace:{n:"Fourneau",c:"#808080",cat:"u"},
  chest:{n:"Coffre",c:"#BC9458",cat:"u"},
  anvil:{n:"Enclume",c:"#3A3A3A",cat:"u"},
  enchanting_table:{n:"T. Enchantement",c:"#1A1A2A",cat:"u"},
  beacon:{n:"Balise",c:"#5CE5E5",cat:"u"},
  torch:{n:"Torche",c:"#FFA500",cat:"l"},
  lantern:{n:"Lanterne",c:"#FFA500",cat:"l"},
  sea_lantern:{n:"Lanterne Marine",c:"#88CCFF",cat:"l"},
  redstone_lamp:{n:"Lampe Redstone",c:"#FF8C00",cat:"r"},
  tnt:{n:"TNT",c:"#FF0000",cat:"r"},
  piston:{n:"Piston",c:"#808080",cat:"r"},
  hopper:{n:"Entonnoir",c:"#808080",cat:"r"},
  dispenser:{n:"Distributeur",c:"#808080",cat:"r"},
  bookshelf:{n:"Bibliothèque",c:"#BC9458",cat:"d"},
  iron_bars:{n:"Barreaux Fer",c:"#A8A8A8",cat:"b"},
  chain:{n:"Chaîne",c:"#4A4A4A",cat:"d"},
  oak_fence:{n:"Clôture Chêne",c:"#BC9458",cat:"w"},
  oak_door:{n:"Porte Chêne",c:"#BC9458",cat:"w"},
  iron_door:{n:"Porte Fer",c:"#D8D8D8",cat:"b"},
  oak_stairs:{n:"Esc. Chêne",c:"#BC9458",cat:"w"},
  oak_slab:{n:"Dalle Chêne",c:"#BC9458",cat:"w"},
  ladder:{n:"Échelle",c:"#BC9458",cat:"w"},
  mossy_cobblestone:{n:"P. Moussues",c:"#6A7A5A",cat:"b"},
  prismarine:{n:"Prismarine",c:"#6BA395",cat:"b"},
  dark_prismarine:{n:"Prismarine Sombre",c:"#3A6A5A",cat:"b"},
  nether_bricks:{n:"Briques Nether",c:"#2C1218",cat:"ne"},
  red_nether_bricks:{n:"Briques N. Rouges",c:"#4A1A1A",cat:"ne"},
  blackstone:{n:"Pierre Noire",c:"#2A2A2A",cat:"ne"},
  basalt:{n:"Basalte",c:"#4A4A4A",cat:"ne"},
  deepslate_bricks:{n:"Briques Deepslate",c:"#4A4A4A",cat:"b"},
  deepslate:{n:"Deepslate",c:"#4A4A4A",cat:"n"},
  magma_block:{n:"Bloc Magma",c:"#8B2500",cat:"ne"},
  end_stone_bricks:{n:"Briques End",c:"#DBD6A0",cat:"e"},
  mud_bricks:{n:"Briques Boue",c:"#8A6A4C",cat:"b"},
  tuff:{n:"Tuff",c:"#6A6A5A",cat:"n"},
  calcite:{n:"Calcite",c:"#DDDDCC",cat:"n"},
  ice:{n:"Glace",c:"#A0C8FF",cat:"n"},
  packed_ice:{n:"Glace Compressée",c:"#88B8FF",cat:"n"},
  blue_ice:{n:"Glace Bleue",c:"#5080FF",cat:"n"},
  snow_block:{n:"Neige",c:"#F0F0F0",cat:"n"},
  clay:{n:"Argile",c:"#9EA4B0",cat:"n"},
  hay_block:{n:"Botte Foin",c:"#C8A82E",cat:"n"},
  melon_block:{n:"Melon",c:"#5A8A2A",cat:"n"},
  pumpkin:{n:"Citrouille",c:"#FF8C00",cat:"n"},
  mushroom_block:{n:"Champignon",c:"#C8A080",cat:"n"},
  white_stained_glass:{n:"Verre Blanc",c:"#FFFFFF",cat:"d"},
  blue_stained_glass:{n:"Verre Bleu",c:"#3C44AA",cat:"d"},
  red_stained_glass:{n:"Verre Rouge",c:"#B02E26",cat:"d"},
  yellow_stained_glass:{n:"Verre Jaune",c:"#FED83D",cat:"d"},
  green_stained_glass:{n:"Verre Vert",c:"#5B7C16",cat:"d"},
  orange_stained_glass:{n:"Verre Orange",c:"#F9801D",cat:"d"},
  light_blue_stained_glass:{n:"Verre Bleu Clair",c:"#3AB3DA",cat:"d"},
  // colored terracotta
  white_terracotta:{n:"T.C. Blanche",c:"#D1B1A1",cat:"b"},
  red_terracotta:{n:"T.C. Rouge",c:"#8D3B2E",cat:"b"},
  brown_terracotta:{n:"T.C. Marron",c:"#4D3223",cat:"b"},
  // wood variants
  spruce_log:{n:"Bûche Épicéa",c:"#3E2812",cat:"w"},
  birch_log:{n:"Bûche Bouleau",c:"#D4C483",cat:"w"},
  jungle_log:{n:"Bûche Jungle",c:"#5A3E1E",cat:"w"},
  acacia_log:{n:"Bûche Acacia",c:"#6A6A3C",cat:"w"},
  dark_oak_log:{n:"Bûche Chêne Noir",c:"#3E2812",cat:"w"},
  cherry_log:{n:"Bûche Cerisier",c:"#E8B4B8",cat:"w"},
  // nether wood
  crimson_planks:{n:"Pl. Cramoisies",c:"#6A1A1A",cat:"ne"},
  warped_planks:{n:"Pl. Distordues",c:"#1A6A6A",cat:"ne"},
  // misc
  slime_block:{n:"Bloc Slime",c:"#78CC48",cat:"u"},
  honey_block:{n:"Bloc Miel",c:"#EB8A08",cat:"u"},
  cobweb:{n:"Toile Araignée",c:"#C8C8C8",cat:"n"},
  soul_fire:{n:"Feu Âme",c:"#00B4D8",cat:"l"},
  crying_obsidian:{n:"Obsid. Pleureuse",c:"#2A0B3A",cat:"ne"},
  end_rod:{n:"Tige End",c:"#E8E8E8",cat:"l"},
  chorus_plant:{n:"Plante Chorus",c:"#6A3A6A",cat:"e"},
  sculk:{n:"Sculk",c:"#0A2A2A",cat:"n"},
};

// Items DB
const ITEMS = [
  {id:"diamond_sword",n:"Épée Diamant",e:"⚔️",cat:"w"},
  {id:"diamond_pickaxe",n:"Pioche Diamant",e:"⛏️",cat:"t"},
  {id:"netherite_sword",n:"Épée Netherite",e:"⚔️",cat:"w"},
  {id:"bow",n:"Arc",e:"🏹",cat:"w"},
  {id:"trident",n:"Trident",e:"🔱",cat:"w"},
  {id:"mace",n:"Masse",e:"🔨",cat:"w"},
  {id:"shield",n:"Bouclier",e:"🛡️",cat:"a"},
  {id:"elytra",n:"Élytres",e:"🦋",cat:"t"},
  {id:"totem_of_undying",n:"Totem",e:"🏅",cat:"s"},
  {id:"golden_apple",n:"Pomme Dorée",e:"🍎",cat:"f"},
  {id:"ender_pearl",n:"Perle Ender",e:"🟣",cat:"s"},
  {id:"eye_of_ender",n:"Œil Ender",e:"👁️",cat:"s"},
  {id:"blaze_rod",n:"Bâton Blaze",e:"🔥",cat:"m"},
  {id:"nether_star",n:"Étoile Nether",e:"⭐",cat:"s"},
  {id:"heart_of_the_sea",n:"Cœur Mer",e:"💙",cat:"s"},
  {id:"saddle",n:"Selle",e:"🐴",cat:"t"},
  {id:"compass",n:"Boussole",e:"🧭",cat:"t"},
  {id:"fishing_rod",n:"Canne Pêche",e:"🎣",cat:"t"},
  {id:"bucket",n:"Seau",e:"🪣",cat:"t"},
  {id:"enchanted_book",n:"Livre Enchanté",e:"📖",cat:"s"},
  {id:"wind_charge",n:"Charge Vent",e:"💨",cat:"w"},
  {id:"cooked_beef",n:"Steak",e:"🥩",cat:"f"},
  {id:"bread",n:"Pain",e:"🍞",cat:"f"},
  {id:"golden_carrot",n:"Carotte Dorée",e:"🥕",cat:"f"},
];

// Mobs DB
const MOBS = [
  {id:"zombie",n:"Zombie",hp:20,e:"🧟",h:1,d:"Brûle au soleil"},
  {id:"skeleton",n:"Squelette",hp:20,e:"💀",h:1,d:"Tire des flèches"},
  {id:"creeper",n:"Creeper",hp:20,e:"💚",h:1,d:"Explosion"},
  {id:"spider",n:"Araignée",hp:16,e:"🕷️",h:1,d:"Nocturne"},
  {id:"enderman",n:"Enderman",hp:40,e:"🟣",h:0,d:"Téléportation"},
  {id:"witch",n:"Sorcière",hp:26,e:"🧙",h:1,d:"Potions"},
  {id:"blaze",n:"Blaze",hp:20,e:"🔥",h:1,d:"Boules de feu"},
  {id:"ghast",n:"Ghast",hp:10,e:"👻",h:1,d:"Explosions"},
  {id:"wither_skeleton",n:"Squelette Wither",hp:20,e:"💀",h:1,d:"Effet Wither"},
  {id:"piglin",n:"Piglin",hp:16,e:"🐷",h:0,d:"Aime l'or"},
  {id:"hoglin",n:"Hoglin",hp:40,e:"🐗",h:1,d:"Charge"},
  {id:"magma_cube",n:"Cube Magma",hp:16,e:"🟧",h:1,d:"Rebondit"},
  {id:"slime",n:"Slime",hp:16,e:"🟢",h:1,d:"Se divise"},
  {id:"phantom",n:"Fantôme",hp:20,e:"👻",h:1,d:"Pas dormi = attaque"},
  {id:"guardian",n:"Gardien",hp:30,e:"🐟",h:1,d:"Laser"},
  {id:"elder_guardian",n:"Ancien Gardien",hp:80,e:"🐟",h:1,d:"Boss"},
  {id:"shulker",n:"Shulker",hp:30,e:"📦",h:1,d:"Lévitation"},
  {id:"vindicator",n:"Vindicateur",hp:24,e:"🪓",h:1,d:"Hache"},
  {id:"pillager",n:"Pillard",hp:24,e:"🏹",h:1,d:"Arbalète"},
  {id:"evoker",n:"Évocateur",hp:24,e:"🧙",h:1,d:"Magie"},
  {id:"ravager",n:"Ravageur",hp:100,e:"🐂",h:1,d:"Très puissant"},
  {id:"warden",n:"Warden",hp:500,e:"🟫",h:1,d:"30 dégâts"},
  {id:"villager",n:"Villageois",hp:20,e:"👨‍🌾",h:0,d:"Commerce"},
  {id:"iron_golem",n:"Golem Fer",hp:100,e:"🤖",h:0,d:"Protège villages"},
  {id:"wolf",n:"Loup",hp:8,e:"🐺",h:0,d:"Apprivoisable"},
  {id:"cat",n:"Chat",hp:10,e:"🐱",h:0,d:"Effraie creepers"},
  {id:"dolphin",n:"Dauphin",hp:10,e:"🐬",h:0,d:"Trésors"},
  {id:"axolotl",n:"Axolotl",hp:14,e:"🦎",h:0,d:"Aquatique"},
  {id:"frog",n:"Grenouille",hp:10,e:"🐸",h:0,d:"Mange slimes"},
  {id:"sniffer",n:"Sniffer",hp:14,e:"🦕",h:0,d:"Fouille sol"},
  {id:"allay",n:"Allay",hp:20,e:"🧚",h:0,d:"Collecte items"},
  {id:"cow",n:"Vache",hp:10,e:"🐄",h:0,d:"Lait, viande"},
  {id:"pig",n:"Cochon",hp:10,e:"🐷",h:0,d:"Porc"},
  {id:"sheep",n:"Mouton",hp:10,e:"🐑",h:0,d:"Laine"},
  {id:"chicken",n:"Poulet",hp:4,e:"🐔",h:0,d:"Œufs"},
  {id:"horse",n:"Cheval",hp:30,e:"🐴",h:0,d:"Montable"},
  {id:"bee",n:"Abeille",hp:10,e:"🐝",h:0,d:"Miel"},
  {id:"wither",n:"Wither",hp:300,e:"💀",h:1,d:"Boss"},
  {id:"ender_dragon",n:"Dragon Ender",hp:200,e:"🐉",h:1,d:"Boss final"},
  {id:"breeze",n:"Breeze",hp:30,e:"💨",h:1,d:"Vent"},
  {id:"armadillo",n:"Tatou",hp:12,e:"🦔",h:0,d:"Écailles"},
];

// Commands DB
const CMDS = [
  {c:"give",s:"/give @s <item> [qty]",d:"Donne un item",e:"/give @s diamond 64"},
  {c:"tp",s:"/tp @s <x> <y> <z>",d:"Téléporte",e:"/tp @s 0 100 0"},
  {c:"effect",s:"/effect give @s <effet> [durée] [niv]",d:"Effet de potion",e:"/effect give @s speed 60 2"},
  {c:"gamemode",s:"/gamemode <mode>",d:"Mode de jeu",e:"/gamemode creative"},
  {c:"fill",s:"/fill <from> <to> <bloc>",d:"Remplit zone",e:"/fill ~ ~ ~ ~10 ~5 ~10 stone hollow"},
  {c:"clone",s:"/clone <from> <to> <dest>",d:"Copie structure",e:"/clone 0 0 0 10 10 10 100 0 0"},
  {c:"setblock",s:"/setblock <pos> <bloc>",d:"Place un bloc",e:"/setblock ~ ~ ~ diamond_block"},
  {c:"summon",s:"/summon <entité> [pos]",d:"Invoque entité",e:"/summon zombie ~ ~ ~"},
  {c:"kill",s:"/kill [cible]",d:"Tuer",e:"/kill @e[type=zombie]"},
  {c:"clear",s:"/clear [cible]",d:"Vider inventaire",e:"/clear @s"},
  {c:"enchant",s:"/enchant @s <ench> [niv]",d:"Enchanter",e:"/enchant @s sharpness 5"},
  {c:"xp",s:"/xp <amount> @s",d:"Donner XP",e:"/xp 1000L @s"},
  {c:"time",s:"/time set <valeur>",d:"Heure",e:"/time set day"},
  {c:"weather",s:"/weather <type>",d:"Météo",e:"/weather clear"},
  {c:"gamerule",s:"/gamerule <règle> [val]",d:"Règle",e:"/gamerule keepInventory true"},
  {c:"execute",s:"/execute <args> run <cmd>",d:"Exécuter",e:"/execute as @a run say hi"},
  {c:"locate",s:"/locate structure <type>",d:"Trouver structure",e:"/locate structure village"},
  {c:"title",s:"/title @s title <texte>",d:"Afficher titre",e:"/title @s title Hello"},
  {c:"particle",s:"/particle <type> <pos>",d:"Particules",e:"/particle flame ~ ~ ~ 1 1 1 0.1 100"},
  {c:"attribute",s:"/attribute @s <attr> <action>",d:"Attributs",e:"/attribute @s generic.max_health base set 40"},
  {c:"spawnpoint",s:"/spawnpoint @s",d:"Spawnpoint",e:"/spawnpoint @s"},
  {c:"worldborder",s:"/worldborder set <taille>",d:"Bordure",e:"/worldborder set 1000"},
  {c:"tag",s:"/tag @s add <tag>",d:"Tag",e:"/tag @s add admin"},
  {c:"scoreboard",s:"/scoreboard objectives add ...",d:"Scores",e:"/scoreboard objectives add kills playerKillCount"},
  {c:"ride",s:"/ride @s mount <entité>",d:"Monter",e:"/ride @s mount @e[type=horse,limit=1]"},
  {c:"damage",s:"/damage @s <amount> [type]",d:"Dégâts",e:"/damage @s 10 minecraft:fall"},
  {c:"forceload",s:"/forceload add <pos>",d:"Forcer chunk",e:"/forceload add ~ ~"},
  {c:"spreadplayers",s:"/spreadplayers <pos> ... @a",d:"Disperser",e:"/spreadplayers 0 0 10 500 @a"},
  {c:"recipe",s:"/recipe give @s *",d:"Toutes recettes",e:"/recipe give @s *"},
  {c:"advancement",s:"/advancement grant @s everything",d:"Tous avancements",e:"/advancement grant @s everything"},
];

function getBlockName(id) {
  return BLOCKS[id]?.n || id.replace(/_/g,' ').replace(/\b\w/g,l=>l.toUpperCase());
}
function getBlockColor(id) {
  return BLOCKS[id]?.c || '#808080';
}